# Generated by Django 4.0.4 on 2022-07-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTracker', '0003_alter_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[(3, 'HIGH'), (2, 'MEDIUM'), (1, 'LOW')], default='low', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='upload_file',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='issue_file/'),
        ),
    ]
